services:
  jenkins:
    # image: jenkins/jenkins:lts-jdk17
    build: .
    container_name: jenkins
    restart: always
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - 8081:8080

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data: